### ISSUE TITLE
dirt and silt not working

### ISSUE THREAD

**Issue by peanutinky** [SirLyle/ExNihiloFabrico#2]
can't use dirt or silt on sieves is this supposed to be that way

**Comment by SirLyle** [comment]
Likely you are using a mesh that doesn't have dirt/sieve recipes. What mesh are you trying to use?

**Comment by SirLyle** [comment]
I have released version 0.3 which has REI support; could you update and tell me if you can see any recipes using dirt/silt in REI for the sieve.

**Comment by SirLyle** [comment]
Since you haven't responded I am assuming that was the issue. If you still have an issue please open a new issue with more information.
