### ISSUE TITLE
Game crashes apon load

### ISSUE THREAD

**Issue by Thresh90** [SirLyle/ExNihiloFabrico#3]
Crashlog https://pastebin.com/hktkxK8L

**Comment by SirLyle** [comment]
This appears to be a crash with Towelette's mixin.

[I have opened an issue with towelette](https://github.com/Virtuoel/Towelette/issues/13)

**Comment by SirLyle** [comment]
Thresh, towelette has released an update after closing my issue with them saying they fixed it; has the update fixed your crash?

**Comment by SirLyle** [comment]
I am closing this as I believe Towelette has fixed it and have not heard to the contrary. Please open a new issue if the problem persists.
